# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 301e23cb8c3cfe141b6993206e2523fd8389004d2c1f6b6b2c494a95150e9c08861aee5fe15dcb897b3b59ff6f4171e72e96a8098968b617283ca7bf27f29b3f

test:
  secret_key_base: 9f5795602fff1abe835042e216f79d3956040b48e7c2c13a8c22a65fcbb8a788fad3fd3e0deeb7e456a1adbe7f955e5342829f5dd93de90cca2044540f2514c6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
